name: Build and Create PR

on:
  push:
    branches:
      - "feature/*"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0.x"

      - name: Install dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --no-restore
        id: test
        continue-on-error: false

  create-pr:
    runs-on: ubuntu-latest
    needs: run-tests
    if: ${{ success() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create developer branch if it doesn't exist
        run: |
          git fetch origin
          if git show-ref --quiet refs/heads/developer; then
            echo "Branch developer already exists."
          else
            echo "Creating branch developer."
            git checkout -b developer
            git push origin developer
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: developer
          title: "Automated PR from feature branch"
          body: "This PR was automatically created after successful tests."
